# Base image for Node.js
FROM node:20

WORKDIR /app

# Copy project files
COPY package*.json /app/
RUN npm install
COPY ./ /app/

# Expose Vite's default port
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
