"""user and profile model and schema updated

Revision ID: 76fae3f9962d
Revises: 0baa07ea2e8e
Create Date: 2025-01-07 17:03:14.647961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fae3f9962d'
down_revision: Union[str, None] = '0baa07ea2e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_roles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'role_id')
    )
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    op.drop_table('profile_roles')
    # ### end Alembic commands ###
