"""Profile Role API and Model updated

Revision ID: dad77b5b7a0f
Revises: e3d463e00b5b
Create Date: 2025-01-08 01:18:37.904865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad77b5b7a0f'
down_revision: Union[str, None] = 'e3d463e00b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
