"""add role attribute to profile model

Revision ID: e942f8d08b64
Revises: c9f32a6e98d6
Create Date: 2025-01-03 04:28:51.893795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e942f8d08b64'
down_revision: Union[str, None] = 'c9f32a6e98d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('profiles', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###
